"""Integrity tests for the Phase 1 order-theoretic atlas.

The atlas at ``benchmarks/foundation/phase1_atlas.csv`` is a
reproducible artifact: it is regenerated by
``tools/build_phase1_atlas.py`` from the deterministic sprinkler and
KR generator. These tests verify that

- the atlas file exists, parses, and covers every cell in the
  Phase 1 grid (3 sizes x 5 seeds x (3 spacetime dimensions + 1 KR
  family) = 60 rows);
- a fresh regeneration produces output byte-identical to the
  recorded artifact, which catches any drift in the generators or
  the estimators.
"""

from __future__ import annotations

import csv
import importlib
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ATLAS_CSV = ROOT / "benchmarks" / "foundation" / "phase1_atlas.csv"
ATLAS_MD = ROOT / "benchmarks" / "foundation" / "phase1_atlas.md"


class Phase1AtlasIntegrityTests(unittest.TestCase):
    def setUp(self) -> None:
        self.atlas_module = importlib.import_module("tools.build_phase1_atlas")

    def _load_rows(self) -> list[dict]:
        with ATLAS_CSV.open(newline="", encoding="utf-8") as fh:
            return list(csv.DictReader(fh))

    def test_files_exist(self) -> None:
        self.assertTrue(
            ATLAS_CSV.exists(),
            msg=f"missing atlas CSV at {ATLAS_CSV}; "
                "run `make regen-phase1`"
        )
        self.assertTrue(
            ATLAS_MD.exists(),
            msg=f"missing atlas markdown at {ATLAS_MD}; "
                "run `make regen-phase1`"
        )

    def test_atlas_covers_every_cell(self) -> None:
        rows = self._load_rows()
        # Sizes x seeds x (3 Minkowski dims + 1 KR) = 60 rows.
        self.assertEqual(len(rows), 60)
        keys = {(r["family"], r["d_spacetime"], r["n"], r["seed"]) for r in rows}
        self.assertEqual(len(keys), 60)
        families = {r["family"] for r in rows}
        self.assertEqual(families, {"minkowski", "kleitman_rothschild"})

    def test_kleitman_rothschild_rows_have_blank_dimension(self) -> None:
        rows = self._load_rows()
        kr_rows = [r for r in rows if r["family"] == "kleitman_rothschild"]
        self.assertTrue(kr_rows)
        for row in kr_rows:
            self.assertEqual(row["d_spacetime"], "")

    def test_regeneration_matches_frozen_artifact(self) -> None:
        # The atlas is reproducible: running the build module on a
        # fresh pass must produce rows identical to the recorded CSV.
        # We compare in-memory (rows from build_rows) against the
        # parsed CSV to avoid an extra write/read cycle.
        live_rows = self.atlas_module.build_rows()
        recorded_rows = self._load_rows()
        self.assertEqual(len(live_rows), len(recorded_rows))
        for live, recorded in zip(live_rows, recorded_rows):
            self.assertEqual(live["family"], recorded["family"])
            self.assertEqual(str(live["d_spacetime"]), recorded["d_spacetime"])
            self.assertEqual(str(live["n"]), recorded["n"])
            self.assertEqual(str(live["seed"]), recorded["seed"])
            self.assertEqual(
                self.atlas_module._format_field(live["mm_dim"]),
                recorded["mm_dim"],
            )
            self.assertEqual(
                self.atlas_module._format_field(live["midpoint_dim"]),
                recorded["midpoint_dim"],
            )
            self.assertEqual(
                self.atlas_module._format_field(live["discrepancy"]),
                recorded["discrepancy"],
            )


if __name__ == "__main__":
    unittest.main()
